payload:
  optional_limit: 2000
  min_word_length: 2
  max_word_length: 25
  max_sentence_length: 4

logger:
  enabled: true
  file: 'log/neo4ruby.log'

redis:
  host: '127.0.0.1'
  port: 6379

simulation:
  alpha: 0.7
  beta: 0.8
  theta: 0.6

  levenshtein:
    max_distance: 3